services:
  dnsmasq:
    restart: unless-stopped
    image: jpillora/dnsmasq
    container_name: dnsmasq
    depends_on:
      - nginx-proxy-manager
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
#      - "8089:8080"
    environment:
      HTTP_USER: ctrlh
      HTTP_PASS: ctrlhctrlh
networks:
  default:
    external: true
    name: nginx-proxy-net
