services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    depends_on:
      - nginx-proxy-manager
    volumes:
      - ../../lib/mariadb:/var/lib/mysql:Z
    networks:
      default: null
      mariadb: null
    env_file:
      - ./.env
# https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    links:
      - mariadb:db
#    ports:
#      - 8080:8080
networks:
  default:
    name: nginx-proxy-net
    external: true
  mariadb:
    name: mariadb-net
